# Dependabot Configuration for vscode-catalog-lens
# Automatically creates PRs for outdated dependencies and GitHub Actions

version: 2
updates:
  # GitHub Actions - Check for action updates weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    # Group all patch updates into a single PR
    groups:
      github-actions-patch:
        patterns:
          - '*'
        update-types:
          - patch
    # Allow both version updates and security updates
    allow:
      - dependency-type: all

  # npm dependencies - Check for package updates weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
    # Group all patch and minor updates
    groups:
      npm-development:
        patterns:
          - '*'
        update-types:
          - patch
          - minor
        dependency-type: development
      npm-production:
        patterns:
          - '*'
        update-types:
          - patch
        dependency-type: production
    allow:
      - dependency-type: all
